application: bear-status
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# static urls
- url: /view/stylesheets/
  static_dir: view/stylesheets
- url: /view/javascript/
  static_dir: view/javascript
- url: /view/images/
  static_dir: view/images

# set up the edit page to require admin access
- url: /date.*
  script: edit.app
  login: admin

- url: /admin.*
  script: edit.app
  login: admin

- url: /edit.*
  script: edit.app
  login: admin

- url: /changelunch.*
  script: edit.app
  login: admin

- url: /revertdate.*
  script: edit.app
  login: admin

- url: .*
  script: main.app

admin_console:
  pages:
  - name: Schedule Editing
    url: /admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: yaml
  version: latest

inbound_services:
- warmup
